version: "3.8"

services:
  app:
    build: .
    container_name: cohabs-chat-mvp
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    # Uncomment for development with live reload:
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    #   - /app/.next
    restart: unless-stopped

  # Optional: Add a development service
  dev:
    build: .
    container_name: cohabs-chat-dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: yarn dev
    profiles:
      - dev
